### ISSUE TITLE
Use fine-grained RBAC for the operator

### ISSUE THREAD

**Issue by jsafrane** [openshift/aws-ebs-csi-driver-operator#18]
The operator now uses `cluster-admin` role. The operator should have its own role that specifies only required permissions.

**Comment by gnufied** [comment]
This is done by CSV PR I think.

**Comment by jsafrane** [comment]
Looks mostly fine. One thing stands out: why the operator needs `hostmount-anyuid` SCC? I don't see it used in the operand.

**Comment by gnufied** [comment]
@bertinatto originally added this. Do you remember if we need this?

**Comment by bertinatto** [comment]
> @bertinatto originally added this. Do you remember if we need this?

No, the initial CSV was a copy from ember-csi's (it shouldn't have been pushed to this repo).

The CSI driver _does_ use the `hostpath` volume plugin, but the operator _does not_, so I think we don't need the `hostmount-anyuid` SCC in the `aws-ebs-csi-driver-operator` SA.
