### ISSUE TITLE
Check why deployment and daemonset are updated when there're no changes

### ISSUE THREAD

**Issue by bertinatto** [openshift/aws-ebs-csi-driver-operator#20]

**Comment by jsafrane** [comment]
Once everything is created and has all replicas, Deployment and DaemonSet are not updated and the operator does nothing. However, I noticed that they end up with `generation: 3`. which is too high. It should be `1`. So the operator modifies them from some reason.

**Comment by jsafrane** [comment]
Checked again, generation is not increased today and it stays at `1` when running the operator from command line.
@bertinatto, is it still an issue?

**Comment by bertinatto** [comment]
No, I'm okay with closing this if it's not incrementing the generation.

/close

**Comment by jsafrane** [comment]
/reopen

When running as a Deployment, I can see the operator updated DaemonSet twice. I can see `Generation: 3`.

**Comment by jsafrane** [comment]
Fixed by https://github.com/openshift/aws-ebs-csi-driver-operator/pull/32
