### ISSUE TITLE
Make sure there are no snapshots using the driver before removing the CR

### ISSUE THREAD

**Issue by bertinatto** [openshift/aws-ebs-csi-driver-operator#22]
Right now it only checks for PVs

**Comment by jsafrane** [comment]
This may be tricky, since snapshot CRDs may not exist when starting the operator. Or should we add dependency on CSI snapshot operator?

**Comment by bertinatto** [comment]
In theory, if snapshot CRDs don't exist when the (aws-ebs-csi-driver-operator) CR is being deleted, there shouldn't be any snapshots, right?

In that case I think it should be OK to go ahead and delete the CR.

**Comment by bertinatto** [comment]
This is no longer valid as this operator is now managed by CSO *and* doesn't interfere when the CR is deleted.

/close
