### ISSUE TITLE
OLM catalog shows operator status as degraded when operator is running normally

### ISSUE THREAD

**Issue by gnufied** [openshift/aws-ebs-csi-driver-operator#45]
![Screenshot from 2020-04-22 10-32-58](https://user-images.githubusercontent.com/278/79995053-b676a600-8484-11ea-8ebf-2159aadfe1f1.png)

**Comment by jsafrane** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1828958, the operator seems to be running fine and there is nothing to be fixed on our side.
/close
