### ISSUE TITLE
Rename Driver type to EBSDriver

### ISSUE THREAD

**Issue by gnufied** [openshift/aws-ebs-csi-driver-operator#47]
A single non-namespaced name interacts poorly with CLI tools and hence it might be a good idea to rename `Driver` to `EBSDriver`.

**Comment by jsafrane** [comment]
We discussed this on today's call and we decided to use `AWSEBSDriver` object in `csi.openshift.io` API group.

Later we're going to add `GCEPDDriver`, `AzureDiskDriver`, `AWSEFSDriver` to the same group.
